# This is a basic workflow to help you get started with Actions

name: Baseos

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_call:
    secrets:
      release_tag:
        description: "Defines the release tag for each layers"
        required: true
      baseos_tag:
        description: "Defines the initial base os tag"
        required: true
      Docker_Hub_Username:
        description: "Contains the DockerHub Username"
        required: true
      Docker_Hub_Password:
        description: "Contains the DockerHub Password"
        required: true
    outputs:
      output1:
        description: "Passing the release tag for this layer"
        value: ${{ jobs.build-and-push.outputs.tag }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.release_tag.outputs.tag }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 
        uses: actions/Checkout@v3
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.Docker_Hub_Username }}
          password: ${{ secrets.Docker_Hub_Password }}

      - name: Test with environment variables
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Setting up release tag for this layer
        id: release_tag
        run: |
          echo "tag=${{ inputs.release_tag }}-${{ env.date }}" >> $GITHUB_ENV
          echo "tag=${{ inputs.release_tag }}-${{ env.date }}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./baseos/
#           username: ${{ secrets.Docker_Hub_Username }}
#           password: ${{ secrets.Docker_Hub_Password }}
          tags: bala001/centos:${{ env.tag }}
          build-args: |
            RELEASE_TAG=${{ inputs.baseos_tag }}
