# This is a basic workflow to help you get started with Actions

name: R-4.1.3_Torsten

# Controls when the workflow will run
on:
  workflow_dispatch:
    # The type of runner that the job will run on
jobs:
  call-workflow1:
    uses: ./.github/workflows/baseos.yaml
    secrets: inherit
  call-workflow2:
    uses: ./.github/workflows/os_utilities.yml
    secrets: inherit