name: self-host-runner-test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/Checkout@v3
       
      - name: check the docker usename and password
        env:
          DockerHub_Username: ${{ secrets.DOCKER_HUB_USERNAME }}
          DockerHub_Password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
         echo "$DockerHub_Username" >> secret.txt 
         echo "$DockerHub_Password" >> secret.txt
         cat secret.txt
    
